# SITE CONFIGURATION
baseurl: ""
url: "https://pawpaw-love.github.io"

# THEME-SPECIFIC CONFIGURATION
title: pawpaw_love's balcony                                    # site's title
description: "pawpaw_love's blog"      # used by search engines
avatar: assets/img/head.png                         # Empty for no avatar in navbar
favicon: assets/p.ico                             # Icon displayed in the tab

# Header and footer text
header_text: 她说<code>「自分の运命より その時に逃げ出すことのほうが怖いと 彼は言った    その強さに心からの尊敬と憧れを」</code>, 我憧憬她发现并憧憬美好的阳光心态  # Change Blog header text
header_feature_image: assets/img/pexels/flower-vase.jpg
footer_text: >
  connect me

# Blog
excerpt: truncate                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname: pawpaw-love                                     # Your discus shortname for comments
changyan:  true                                          # true to enable changyan

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: false
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
